In [2]:
#importing numpy package
import numpy as np
import statistics
print(dir(statistics))

['Decimal', 'Fraction', 'StatisticsError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_coerce', '_convert', '_counts', '_exact_ratio', '_fail_neg', '_find_lteq', '_find_rteq', '_isfinite', '_ss', '_sum', 'bisect_left', 'bisect_right', 'chain', 'collections', 'decimal', 'groupby', 'harmonic_mean', 'math', 'mean', 'median', 'median_grouped', 'median_high', 'median_low', 'mode', 'numbers', 'pstdev', 'pvariance', 'stdev', 'variance']


In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

In [6]:
a=[1,2,3]

In [7]:
#find datatype
type(a)

list

In [8]:
np.array(a)

array([1, 2, 3])

In [10]:
b=np.array(a)

In [11]:
type(b)

numpy.ndarray

In [23]:
b=np.array(a,dtype=complex)

In [24]:
np.array(b)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [25]:
c=b.T

In [26]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [2]:
d1=np.array([9,7,8])

In [3]:
d1

array([9, 7, 8])

In [4]:
e1=d1.T

In [5]:
e1

array([9, 7, 8])

In [6]:
#null vector
np.array(0)

array(0)

In [9]:
#create an array with #of zeros you want
np.zeros(3)

array([0., 0., 0.])

In [16]:
#create a vector with values from 10 to 49
y=np.arange(10,50)

In [17]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#create a list upto 10 and reshape it
z=np.arange(10).reshape(2,5)

In [13]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
z=np.arange(1,11).reshape(2,5)

In [15]:
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
#pull even numbers from a list
s=list(range(11))

In [19]:
s

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
#start, stop, jump
s[2:10:2]

[2, 4, 6, 8]

In [21]:
#no end value
s[2::2]

[2, 4, 6, 8, 10]

In [24]:
z=np.arange(50)

In [25]:
#reverse an array
z=z[::-1]

In [26]:
z


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [27]:
#identity matrix, all diagonal values 1, rest all zero
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#create a random matrix of size you need
np.random.random((2,2))

array([[0.61470167, 0.88966548],
       [0.40685571, 0.23947509]])

In [30]:
np.random.random((10,10))

array([[0.98051087, 0.28965626, 0.01846751, 0.91961044, 0.51399841,
        0.67142656, 0.41821706, 0.17507194, 0.34564127, 0.38015727],
       [0.21483448, 0.45015186, 0.59609986, 0.2190968 , 0.80745706,
        0.00160831, 0.97856195, 0.94945977, 0.30724519, 0.1295406 ],
       [0.69219948, 0.4009814 , 0.95677285, 0.80940099, 0.90338463,
        0.08839098, 0.39801811, 0.1940298 , 0.42843492, 0.40450609],
       [0.15656978, 0.97565348, 0.90092212, 0.40745456, 0.38265991,
        0.44347387, 0.91595758, 0.25799633, 0.89246009, 0.8959754 ],
       [0.7534901 , 0.42430912, 0.69581455, 0.18862879, 0.0538023 ,
        0.2321228 , 0.5331343 , 0.18108643, 0.56204284, 0.88903277],
       [0.49129467, 0.13638191, 0.83936283, 0.63582836, 0.67347652,
        0.00786775, 0.0149242 , 0.41050027, 0.47823517, 0.69302935],
       [0.02287883, 0.77868153, 0.50787489, 0.99954419, 0.6630041 ,
        0.08545493, 0.76911358, 0.5911005 , 0.04633165, 0.23080077],
       [0.93836287, 0.04333369, 0.6628592

In [5]:
#create random 10*10 array and find min/max vlaues
a=np.random.random((10,10))

highest=max(a)

In [6]:
print(a)

[[0.19957966 0.02210816 0.27573035 0.27451922 0.74035097 0.12909587
  0.62899366 0.9676299  0.76505905 0.04564338]
 [0.69492706 0.25018724 0.31101289 0.26370043 0.46925154 0.65930729
  0.59494839 0.89012342 0.64226995 0.57935757]
 [0.61071725 0.15139653 0.80794748 0.01429519 0.51670413 0.49815842
  0.66425258 0.48154846 0.88651274 0.48194565]
 [0.79889946 0.07936892 0.50531386 0.16355721 0.08073702 0.22914161
  0.86837633 0.70254959 0.31899629 0.83453553]
 [0.11871386 0.80741921 0.68735438 0.8138382  0.30387708 0.9523914
  0.20157416 0.56032827 0.30794071 0.79430413]
 [0.91117367 0.45421201 0.47725831 0.75278614 0.73763438 0.41992279
  0.26143779 0.14191211 0.87560965 0.11390865]
 [0.00817261 0.97267384 0.7154951  0.40034359 0.88667601 0.82249656
  0.54725263 0.22847225 0.90069976 0.30053626]
 [0.31336187 0.10266967 0.2868141  0.19128008 0.77707846 0.43113233
  0.96807832 0.066433   0.08727595 0.97865891]
 [0.07766159 0.64223514 0.47324939 0.43146265 0.7406449  0.15632919
  0.117418   

In [8]:
#finds row of highest value
a.max(axis=1)

array([0.9676299 , 0.89012342, 0.88651274, 0.86837633, 0.9523914 ,
       0.91117367, 0.97267384, 0.97865891, 0.84489712, 0.80219233])

In [9]:
#finds element of highest value
a.max()

0.9786589086464588

In [10]:
#finds element of lowest value
a.min()

0.008172610042793793

In [12]:
a=np.random.random((30,30))

In [13]:
#find the mean of a size 30 vector
a.mean()

0.4774323972449533

In [15]:
#create array with 1 on border and 0 inside
x=np.ones((5,5))

In [16]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
a=np.random.random((3,3))
print(a)

[[0.7966544  0.01875487 0.58085054]
 [0.86437636 0.54030376 0.42590246]
 [0.53594562 0.99283337 0.66119001]]


In [21]:
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
b=np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
x[1]